name: Run Tests

on:
  push:
  repository_dispatch:

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: npm install
      - uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      # Rather than using `yarn build`, split these commands into their own step.
      - run: forge build
      - run: yarn typechain

      - name: Run tests
        run: forge test
